
// This file is autogenerated.
// It was added by doctest_registerlibrary.cmake in order to ensure that the tests are properly run by DocTest.
// Please commit it if needed, it will be modified only if new files are added.

int DocTestRegister_f3521254_e571_4345_b818_16c2a8f67761();
int DocTestRegister_89f27c0b_f043_4d20_9cdd_d0ad9216a70a();


int DocTestRegister()
{
  int dummy_sum = 0;
  dummy_sum += DocTestRegister_f3521254_e571_4345_b818_16c2a8f67761();
  dummy_sum += DocTestRegister_89f27c0b_f043_4d20_9cdd_d0ad9216a70a();

  return dummy_sum;
}
